// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AestheticStep: typeof import('./src/components/steps/AestheticStep.vue')['default']
    Amogus: typeof import('./src/components/themes/Amogus.vue')['default']
    AmongUsCustom: typeof import('./src/components/extras/AmongUsCustom.vue')['default']
    BackButton: typeof import('./src/components/buttons/BackButton.vue')['default']
    BarredTopIconLayout: typeof import('./src/components/layouts/BarredTopIconLayout.vue')['default']
    BigTimeLayout: typeof import('./src/components/layouts/BigTimeLayout.vue')['default']
    BottomLayout: typeof import('./src/components/layouts/BottomLayout.vue')['default']
    BottomThreeBarredLayout: typeof import('./src/components/layouts/BottomThreeBarredLayout.vue')['default']
    CheckpointStep: typeof import('./src/components/steps/CheckpointStep.vue')['default']
    ContinueButton: typeof import('./src/components/buttons/ContinueButton.vue')['default']
    CornerLayout: typeof import('./src/components/layouts/CornerLayout.vue')['default']
    CustomImage: typeof import('./src/components/themes/CustomImage.vue')['default']
    ExportStep: typeof import('./src/components/steps/ExportStep.vue')['default']
    ImageUpload: typeof import('./src/components/extras/ImageUpload.vue')['default']
    IntroStep: typeof import('./src/components/steps/IntroStep.vue')['default']
    LayoutStep: typeof import('./src/components/steps/LayoutStep.vue')['default']
    LeftListLayout: typeof import('./src/components/layouts/LeftListLayout.vue')['default']
    ModernSleek: typeof import('./src/components/themes/ModernSleek.vue')['default']
    NoLayout: typeof import('./src/components/layouts/NoLayout.vue')['default']
    NoTheme: typeof import('./src/components/themes/NoTheme.vue')['default']
    RetroPurple: typeof import('./src/components/themes/RetroPurple.vue')['default']
    RightListLayout: typeof import('./src/components/layouts/RightListLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedStatItem: typeof import('./src/components/items/SelectedStatItem.vue')['default']
    StandardLayout: typeof import('./src/components/layouts/StandardLayout.vue')['default']
    StatisticItem: typeof import('./src/components/items/StatisticItem.vue')['default']
    StatisticItemCentered: typeof import('./src/components/items/StatisticItemCentered.vue')['default']
    StatisticsStep: typeof import('./src/components/steps/StatisticsStep.vue')['default']
    ThemesStep: typeof import('./src/components/steps/ThemesStep.vue')['default']
    TopIconLayout: typeof import('./src/components/layouts/TopIconLayout.vue')['default']
    TopLayout: typeof import('./src/components/layouts/TopLayout.vue')['default']
  }
}
